name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Update package-lock.json
        run: |
          rm -rf package-lock.json node_modules
          npm install

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --prod --output-path docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

      - name: Update repo description
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $GH_TOKEN | gh auth login --with-token
          gh repo edit --homepage "https://${{ github.repository_owner }}.github.io/${{ github.repository }}" .